language: node_js
node_js:
  - "10.9"
addons:
  chrome: stable
before_script:
  - npm install grunt-cli rollup -g
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
